name: Day In The Life
favicon: null
layout_spectrum: 0.50994
typography_spectrum: 0.80733
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b1014'
    - '#8d5d46'
    - '#36485c'
    - '#a1a7a7'
    - '#e8e2d6'
  brandStrength: 0.5
  lightness: 0.18751709535717964
  saturation: 0.7411198045592755
  rhythmicContrast: 0.5267966326791793
purpose: []
