name: Day In The Life
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8382376825902611
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f1ed'
    - '#00b3fd'
    - '#afafaf'
    - '#333333'
    - '#db6060'
  brandStrength: 0.9855604644399136
  lightness: 0.18751709535717964
  saturation: 0.7411198045592755
  rhythmicContrast: 0.5267966326791793
purpose: []
